version: 2.0
jobs:
  build:
    docker:
      - image: enco164/nr1-build-circle-ci:0.0.3
    steps:
      - checkout
      - run: npm install --prefix ./synthetics/monitors
      - run: npm install --prefix ./nerdlets/disagreeable-payment
      - run:
          name: build-suynthetics-monitors
          command: npm run build --prefix ./synthetics/monitors
      - run:
          name: build-new-relic-one-nerdlets
          command: npm run build --prefix ./nerdlets/disagreeable-payment
